    version: '2'
    services:
        gps2trip:
            image: gps2trip
            volumes:
             - $HOST_VOLUME_FOLDERPATH:$CONTAINER_VOLUME_FOLDERPATH
            command: Rscript /home/gps2trip/estimate_yesterday_bat.R /home/gps2trip/ /home/google-transit/ $INPUT_DATA_FOLDERPATH $OUTPUT_DATA_FOLDERPATH $DATA_FORMAT
